apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ccphxvolume
  labels:
    name: ccphxvolume
spec:
  template:
    metadata:
      labels:
        name: ccphxvolume
    spec:
      containers:
      - name: hxvolume
        image: registry.ci.dfj.io/metacloud_ccp/hxvolume:0.5.0-18.gefcd90c.premerge
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["/bin/sh", "-c", "while true; do sleep 2; done"]
      initContainers:
      - name: iscsi-initiator
        image: registry.ci.dfj.io/metacloud_ccp/hxvolume:0.5.0-18.gefcd90c.premerge
        command: ['sh', '-c', 'SCSI_initiator_name=$(iscsi-iname); echo $SCSI_initiator_name > /etc/iscsi/initiatorname.iscsi']
      - name: hxvolume-copy
        image: registry.ci.dfj.io/metacloud_ccp/hxvolume:0.5.0-18.gefcd90c.premerge
        command: ['sh', '-c', 'cp /hxcache/hxvolume /hxhostmount/']
        volumeMounts:
          - mountPath: /hxhostmount
            name: hxvolume-mount
          - mountPath: /etc/iscsi
            name: iscsi-volume
      volumes:
        - name: hxvolume-mount
          hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/hyperflex~hxvolume/
        - name: iscsi-volume
          hostPath:
            path: /etc/iscsi
